sudo: required
services:
  - docker

before_install:
  - docker build -t 36351620/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 36351620/react-test npm test -- --coverage

after_success:
  - docker build -t 36351620/multi-client ./client
  - docker build -t 36351620/multi-nginx ./nginx
  - docker build -t 36351620/multi-server ./server
  - docker build -t 36351620/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 36351620/multi-client
  - docker push 36351620/multi-nginx
  - docker push 36351620/multi-server
  - docker push 36351620/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker1
  env: MultiDocker1-env
  bucket_name: elasticbeanstalk-ap-south-1-515222663508
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
